baseurl = "http://www.hbiotech.com"
languageCode = "en-us"
title = "Harvard Undergraduate Biotechnology Association"
theme = "hugo-creative-theme"
[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more informtion take a look at the README.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Harvard Undergraduate Biotechnology Association"
	description = "Javascript. Python. Beautiful Design."

	# The path must be relative to the static folder
	favicon = "/img/favicon.ico"


	# Navigation
	[params.navigation]
		brand = "Harvard Biotech"

		[params.navigation.links]
			about  = "About"
			services  = "Services"
			donate = "Donate"
			advisors = "Advisors"
			team = "Team"
			contact = "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Harvard Undergraduate Biotechnology Association"
		buttonText = "What We Do"


	# About section
	[params.about]
		headline    = "HBio"
		description = "is a forum for students to learn about various aspects of the biotechnology and explore the different intersections of research and industry through interactive participation and meetings with the most powerful people in the field."
		buttonText  = "View More"


	# Service section
	[params.services]
		headline = "What We Do"

        [[params.services.list]]
            icon = "fa-diamond"
            title = "Events"
            description = "Group dinners to discuss topics and news in biotech."

        [[params.services.list]]
			icon = "fa-paper-plane"
			title = "Passion"
			description = "Dinners with faculty and industry leaders in a small setting that encourages interaction"

		[[params.services.list]]
            icon = "fa-newspaper-o"
            title = "Drive"
            description = "Off-campus events including company tours. "

        [[params.services.list]]
            icon = "fa-heart"
            title = "Development Skill"
            description = "Guest lectures and symposiums with people on the cutting edge of research."


    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	[params.aside]
		headline = "Donate Now"

	# About section
	[params.advisors]
		headline    = "Advisor - Gregory Verdine"
		description = "Greg Verdine is the Director of the Chemical Biology Initiative and the Program in Cancer Chemical Biology at the Dana-Farber Cancer Institute, and is a Harvard College Professor. His Dana-Farber research effort aims to discover entirely new molecular classes of drugs to tackle so-called “undruggable” targets. Verdine is a senior advisor to Third Rock Ventures and the Texas Pacific Group, and has founded, co-founded or re-founded six biopharmaceutical companies"
		buttonText  = "View More"
		img = "gregoryverdine.jpg"

	[params.team]
		headline = "Our Team"
		[[params.team.list]]
				img = "lena.png"
				title = "Lena Afeyan"
				bio = "President"
		[[params.team.list]]
			img = "carlo.png"
			title = "Carlo Bocconcelli"
			bio = "Vice President"
		[[params.team.list]]
			img = "Mikhail1.jpg"
			title = "Mikhail Grushko"
			bio = "Director of Finance"
		[[params.team.list]]
				img = "scott.jpg"
				title = "Scott Xiao"
				bio = "Co-Director of Programming"
		[[params.team.list]]
			img = "brandon.jpg"
			title = "Brandon Wright"
			bio = "Co-Director of Programming"
		[[params.team.list]]
			img = "joy.jpg"
			title = "Joy Jin"
			bio = "Treasurer"
		[[params.team.list]]
			img = "michael.jpg"
			title = "Michael Liu"
			bio = "Co-Director of Recruitment"
		[[params.team.list]]
				img = "jett.png"
				title = "Jett Crowdis"
				bio = "Co-Director of Recruitment"
		[[params.team.list]]
				img = "raul.png"
				title = "Raul Jordan"
				bio = "Co-Director of Technology"
		[[params.team.list]]
				img = "avi.jpg"
				title = "Avinash Lal"
				bio = "Co-Director of Technology"
		[[params.team.list]]
			img = "erica.png"
			title = "Erica Budina"
			bio = "Chair of Internal Development"
	# Contact section
	[params.contact]
		headline = "Contact Us"
		email = "biotechassoc@gmail.com"
